G14_Suppliers/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eProx.urls')),
    path('eProx/',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls', namespace="order")),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create_order',views.create_order,name = 'create'),
    path('create/', views.order_create, name='order_create'),
    path('checkout/',views.checkoutDetails, name= 'checkout'),
    path('checkouted/', views.checkout_view,name='checkouted')
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from eProx.models import *


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': False})
    return render(request, 'cart/detail.html', {'cart': cart, 'cart_product_form':cart_product_form})

cart/templates/cart/detail.html
 {% load static %}
 {% block title %}
 <div id="title">
 <h2>Your shopping cart</h2></div>
 {% endblock%}
 
 {% block content%}
 <!DOCTYPE html>
 <html lang="en">
     <head>
         <meta charset="UTF-8">
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="viewport" content="width=device-width,initial-scale=1.0">
         <title>your cart</title>
         <link rel="stylesheet" href="https://pro.fontawesome.com/releases/vs.10.0/css/all.css"/>
 
         <link rel="stylesheet" href="{% static 'CSS/cart.css' %}">
     </head>
 <body>
     {% if cart %}  
     <section id="cart" class="section-p1">
         <table width="100%">
             <thead>
                 <tr>
                     <td>remove</td>
                     <td>image</td>
                     <td>product</td>
                     <td>price</td>
                     <td>quantity</td>
                     <td>Total</td>
                 </tr>
             </thead>
             <tbody>
                 <tr>
                     {% for item in cart %}
                     {% with product=item.product %}
 
 
                         <tr>
                             
                             <td><i class="fas fa-times-circle"><a href="{% url 'cart:cart_remove' product.id %}">X</a></i></td>
                             <td class="hidden-xs " width="20" height="19"><a href="{{product.get_absolute_url}}"><img src="{{ product.picture.url }}" alt="{{item.description}}" style="max-width: 100px; max-height: 100px;"></a></td>
                             <td><h3>{{ product.name }}</h3></td>
                             <td><h3>shs.{{ item.price }}</h3></td>
                             <td><h3>{{item.quantity}}</h3> 
                                 <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                     {% csrf_token %}
                                     {{ item.update_quantity_form.quantity }}
                                     {{ item.update_quantity_form.override }}
                                     <input class="btn btn-primary btn-sm" style="color: rgb(0, 0, 0);" type="submit"
                                         value="Update">
                                 </form></td>
                             <td><h3>shs.{{ item.total_price }}</h3></td>
                         </tr>
                         {% endwith %}
                         {% endfor %}
                 </tr>
                 
                 
             </tbody>
         </table>
     </section>
     <section id="cart-add" class="'section-p1">
         <div id="coupon">
             <h3>Options</h3>
             <div>
                 
                 <a href="{% url "product" %}"><button onclick=window.location='{% url "product" %}'class="normal">continue shopping</button></a>
             </div>
             <div>
                 
                 <form action="{% url 'cart:cart_clear' %}">
                     <button class="normal">Clear Cart</button>
                 </form>
             </div>
         </div>
 
         <div id="subtotal">
             <h3>Cart Totals</h3>
             <table>
                 <tr>
                     <td><strong>ITEMS</strong></td>
                     <td><strong>AMOUNT</strong></td>
                 </tr>
                 
                 <tr>
                     
                     <td><h4>Total items: {{ cart.get_total_quantity }} </h4></td>
                     <td><strong>shs.{{ cart.get_total_price|floatformat:"2" }}</strong></td>
                 </tr>
             </table>
             {% if user.is_authenticated %}
                         
             
             <button class="normal" onclick=window.location="{% url 'order:create' %}">Proceed To Checkout</button>
             {% else %}
             
             {% endif %}
 
         </div>
         {% else %}
 <h1 class="text-center">Your Shopping Cart is Empty!</h1>
 <div id="cart-empty">
     <button class="normal"><a href="{% url 'home' %}" >Go to Home
     </a></button>
 </div>
     </section>
 </body>
 </html>
 {% endif %}
 {% endblock %}

cart/templates/cart/shop_checkout.html
{% extends "shop/base/base.html" %}
{% load static %}

{% block title %}
Your shopping 
{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap4.css' %}">
</head>

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="{% url 'home' %}">Home</a> <span class="mx-2 mb-0">/</span> <strong
                    class="text-black">Cart</strong></div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <form class="col-md-12" method="post">
                <div class="site-blocks-table">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>{% for item in cart %}
                                {% with product=item.product %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ product.image.url }}" alt="Image" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ product.name }}</h2>
                                </td>
                                <td>${{ item.price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                {% csrf_token %}
                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input class="btn btn-outline-primary js-btn-plus" type="submit"
                                                    value="Update">
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <td>${{ item.total_price }}</td>
                                <td><a href="{% url 'cart:cart_remove' product.id %}"
                                        class="btn btn-primary btn-sm">X</a></td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                            </tr>

                        </tbody>
                    </table>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
                    
                    <div class="col-md-6">
                        <button class="btn btn-outline-primary btn-sm btn-block">Checkout</button>
                    </div>
                </div>
                <div class="row">
                   
                </div>
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ cart.get_total_price_after_discount|floatformat:"2" }}</strong>
                            </div>
                        </div>

                        <div class="row">
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}