G14_Suppliers/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eProx.urls')),
    path('eProx/',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls', namespace="order")),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

eProx/urls.py
from django.urls import path
from .import views
from .views import CustomLoginView, CustomLogoutView
#the urls of the app
urlpatterns = [
    path('', views.home, name = "home"),
    path('product/',views.product, name = "product"),
    path('business1/',views.business, name = "business1"),
    path('signup/',views.register, name = "signup"), 
    path('bessreg/',views.register_bss, name = "bssreg"), 
    # path('checkout/',views.checkout, name ="checkout"),
    path('product',views.product, name ="product"),
    
    path('regproduct',views.regproduct, name='regproduct'),
    path('regbusiness',views.regbusiness, name='regbusiness'),
    
    path('search',views.search, name='search'),
    path('category/<str:foo>',views.category, name='category'),
    path('product/<int:pk>',views.productcard, name='productcard'),
    # path('profile_general/',views.profile_general, name='profile_general'),
    # path('profile_recieve/<int:id>',views.profile_receive, name='profile_recieve'),
    
    path('orderstatus/', views.orderstatus, name='orderstatus'),
    path('manage',views.manage, name='manage'),
    path('business',views.business, name='business'),
    path('userinfo',views.customer_info, name='userinfo'),
    path('delete-product/<int:product_id>/',views.delete_product, name='delete_product'),
    path('delete-order/<int:order_id>/', views.delete_order, name='delete_order'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('edit/', views.edit_business, name='edit_business'),
    
    path('mark_delivered/<int:order_id>/', views.mark_delivered, name='mark_delivered'), 
    path('place/', views.place_order, name='place'),
]

eProx/forms.py
from django.forms import ModelForm
from .models import *
from order.models import *
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



#This is python form that is to register new users in the database.
class SignUpForm(UserCreationForm):
	
	class Meta:
		model = User
		fields = ('username', 'password1', 'password2') 	# username is the username of the new user.
            												#password1 is the first password the user enters.
															# password2 is the confirmation of the first password entered by the user

		        
class BssRegForm(UserCreationForm):
	
	class Meta:
		model = User
		fields = ('username', 'password1', 'password2')    

#The product form is for registering  new products onto the website.
class Productform(ModelForm):
    class Meta:
        model=Product
        fields="__all__"# This extracts all the fields of the product model.
        excludes = 'business'
        

#The business form is for registering  new businesses onto the website.
class Businessform(ModelForm):
    class Meta:
        model = Business
        fields="__all__" # This extracts all the fields of the Buiness model.

class Customerform(ModelForm):
    class Meta:
        model = Customer
        fields="__all__" #         

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']
        			
                    
class ProfileUserForm(forms.ModelForm):
    class Meta:
            model = Profile
            fields = ['name','Company','bio','birthday','country','phone','email','website']


class BusinessEditForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = "__all__"     
          

        

eProx/views.py
from django.shortcuts import render,redirect,get_object_or_404,HttpResponseRedirect
from .models import *
from order.models import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User,Group
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse
from.forms import *
from django.http import JsonResponse
import json
from .decorators import allowed_users
from django.http import HttpResponse,HttpResponseNotAllowed,HttpResponseNotFound
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST

from cart.forms import *
from order.views import  make_order


#This is the view for the home page.
def home(request):
    products = Product.objects.all()#This is a query expression in  that retrieves all the objects from the Product table in the database.
    context ={'products':products,}
    return render(request, 'eProx/homepage.html',context)


#This is a view for the product page which shows all products available in the database.
#@allowed_users(allowed_roles=['Customer','Admin'])
def product(request):
    cart_product_form = CartAddProductForm()
    products = Product.objects.all()  #This is a query expression in  that retrieves all the objects from the Product table in the database.
    context ={'products':products,'order':order,'cart_product_form':cart_product_form}
    return render(request,'eProx/product.html',context)



#Each product is assigned a product card for organisation and easy viewing .
def productcard(request,pk):
    cart_product_form = CartAddProductForm()
    product= Product.objects.get(id=pk) 
    context = {'cart_product_form':cart_product_form,'product':product, }
    #This retrieves a specific instance of the Product model from the database based on its primary key used as a product id.
    return render(request,'eProx/productcard.html',context)

    


#@allowed_users(allowed_roles=['Customer','Admin'])
def category(request,foo):
    #just replacing hyphens with spaces...nothing much
    foo = foo.replace('-',' ')
    try:
        category=Category.objects.get(name=foo)
        products= Product.objects.filter(category=category)
        return render(request,'eProx/category.html',{'products':products, 'category':category})
    except:
        return redirect('home')


# This is for product registration.
@login_required(login_url= "login")
@allowed_users(allowed_roles=['Business','Admin'])
def regproduct(request):
    form = Productform()
    current_user=request.user
    user_business=Business.objects.get(user=current_user)

    if request.method == "POST":
        form= Productform(request.POST,request.FILES)
        if form.is_valid():#the product information is only saved in the database if it is valid as per the product model.
            form.instance.business=user_business
            form.save()
            return redirect ('manage')# once the product information is valid and saved in the database,the user is re-directed 
          
        else:
            return render(request,'eProx/productreg.html',{'form':form})
    else:           
        return render(request,'eProx/productreg.html',{'form':form})
    
# The regbusiness view is for registering new businesses.
#@allowed_users(allowed_roles=['Business','Admin'])
def regbusiness(request):
    form = Businessform()
    user = request.user
    if request.method =="POST":
        form= Businessform(request.POST,request.FILES)
        if form.is_valid(): #The business information must be valid for it to be saved in the database
            form.instance.user = user
            form.save()
            return redirect ('business')
        else:
            return render(request,'eProx/regbusiness.html',{'form':form})
    else:           
        return render(request,'eProx/regbusiness.html',{'form':form}) 



# This is the search view
#@allowed_users(allowed_roles=['Customer','Admin'])
def search(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')
        searched_products = Product.objects.filter(name__icontains=searched)

        if not searched_products:
            messages.info(request, "The product does not exist.")   
            referring_url = request.META.get('HTTP_REFERER')
            if referring_url:
                return HttpResponseRedirect(referring_url)
            else:
                return HttpResponseRedirect(reverse('product'))
        else:
            return render(request, 'eProx/search.html', {'searched': searched_products})
    else:
        return render(request, 'eProx/search.html', {})
      

    
#This logs the current user.
@login_required
def place_order(request):
    return make_order(request)  
    
# this adds items to the cart
# @allowed_users(allowed_roles=['Customer','Admin'])
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, 'eProx/product.html', context)

# The register view is for signing up new users.
def register(request): 
    form = SignUpForm()
    if request.method =="POST":
        form= SignUpForm(request.POST)
        if form.is_valid(): #The user information must be valid for it to be saved in the database
            new_user=form.save()
            # user = form.instance.user
            Customer.objects.create(
                user=new_user,
                name = new_user.username,
                email = new_user.email,
            )
    
            group = Group.objects.get(name='Customer')
            new_user.groups.add(group) 
     
            username= form.cleaned_data.get('username')   #This extracts the cleaned and validated value of the 'username' field from the form
            password= form.cleaned_data.get('password1')  #This extracts the cleaned and validated value of the 'password1' field from the form
            user = authenticate(request,username=username,password=password)
            if user is not None: #once the user is fully registered and saved in the database, they are now authenticated and logged in
                login(request,user)
                return redirect ('home')
        else: 
            return redirect ('home')
    else:           
        return render(request,'eProx/signup.html',{'form':form})
    


def register_bss(request):
    form = BssRegForm()
    if request.method =="POST":
        form= SignUpForm(request.POST)
        if form.is_valid(): #The business information must be valid for it to be saved in the database
            new_business=form.save()

            group = Group.objects.get(name='Business')
            new_business.groups.add(group)
     
            username= form.cleaned_data.get('username')   #This extracts the cleaned and validated value of the 'username' field from the form
            password= form.cleaned_data.get('password1')  #This extracts the cleaned and validated value of the 'password1' field from the form
            user = authenticate(request,username=username,password=password)
            if user is not None: #once the user is fully registered and saved in the database, they are now authenticated and logged in
                login(request,user)
                return redirect ('regbusiness')
        else: 
            return redirect ('regbusiness')
    else:           
        return render(request,'eProx/bssreg.html',{'form':form})    
        




def order(request, status=None):
    if request.user.is_authenticated:
        customer = request.user.customer
        if status:
            orders = Order.objects.filter(customer=customer, status = status)
        else:
            orders = Order.objects.filter(customer = customer)





# @allowed_users(allowed_roles=['Customer','Admin'])
# def customer_info(request):
#     if request.user.is_authenticated:
#         user = request.user
#         customer = Customer.objects.get(user=user)
#         orders = Checkout.objects.filter(user=user)
#         return render(request, 'eProx/userprofile.html', {'customer': customer, 'orders': orders})
#     else:
#         return render(request, 'eProx/homepage.html')



def mark_delivered(request, order_id):
    if request.method == 'POST':
        order = Order.objects.get(id=order_id)
        order.status = 'Delivered'
        order.save()
    return redirect('userinfo')


# @allowed_users(allowed_roles=['Business', 'Admin'])
# def manage(request):
#     try:
#         business = get_object_or_404(Business, user=request.user)
#         products = Product.objects.filter(business=business)
#         # orders = Order.objects.filter(customer__business__user=request.user)
#         orders = Order.objects.filter(product__in=products).distinct()
#         items= OrderedProducts.objects.all()

#         checkout_info = []
#         for user in orders:
#             checkout_info = Checkout.objects.filter(user=user).first()
#             if checkout_info:
#                 checkout_info.append(checkout_info)




#         return render(request, 'eProx/manage.html', {
#             'products': products,
#             'orders': orders,
#             'items':items
#         })
#     except Business.DoesNotExist:
#         return HttpResponse("Business not found.")
#     except Order.DoesNotExist:
#         return HttpResponse("No orders found.")
#     except Exception as e:
#         return HttpResponse(f"An error occurred: {e}")


@login_required
@allowed_users(allowed_roles=['Business','Admin'])
def edit_business(request):
    business = request.user.business
    if request.method == 'POST':

eProx/templates/eProx/business1.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>eprox</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" >

        <link rel="stylesheet" href="{% static 'CSS/styles.css' %}">
    </head>
    <body>
        <section id="header">
            <img src="{% static 'images/logo.jpg' %}" class="logo" alt="">
            <div>
                <ul id="navbar">
                   
                    <!-- <li><a  href="{%url 'home'%}">HOME</a></li> -->
                    
                </ul>
            </div>
           
        </section>




<!DOCTYPE html>
<html>
    <head>
        <meta cahrset="UTF-8"/>
        <title>business Profile</title>
        <link rel="stylesheet" href="{% static 'css/business1.css' %}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
        
        <style>
    .container {
    display: flex; /* Use flexbox layout */
    align-items: center; /* Align items vertically */
    justify-content: space-between; /* Space between logo and business info */
    max-width: 800px;
    margin: 20px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

.logo-container {
    flex: 1; /* Allows the logo container to grow */
    text-align: left; /* Aligns the logo to the left */
}

.logo {
    width: 150px; /* Adjust size as needed */
    height: 150px; /* Adjust size as needed */
    border-radius: 50%; /* Makes the image circular */
}

.business-info {
    flex: 2; /* Allows the business info container to grow */
    text-align: left; /* Aligns the business info to the left */
}

h1, h2, p {
    margin: 0; /* Removes default margin */
}

</style>

    </head>
    <body>
       

            <div class="container mt-5">
                <div class="logo-container">
                    <img src="" alt="Business Logo" class="logo">
                </div>
                
                <div class="business-info">
                    <h1>{{ business_profile.name }}</h1>
                    <h3>{{ business_profile.location }}</h3>
                    
                    <p><strong>{{ business_profile.email }}</strong></p>
                    <p><strong>{{ business_profile.contacts }}</strong></p>
                    <p><strong>{{ business_profile.description }}</strong></p>
                </div>
            </div>
            

            <section class="main">
                <div class="main-top">
                    <h3>INVENTORY   MANAGEMENT</h3>
                    
                </div>
                <div class="main-products">
                    
                    <div class="card">
                        <i class="fas fa-laptop-code"></i>
                        <h3>Manage your Inventory</h3>
                        <p>view your orders and products.</p>
                        <a href="{% url 'manage' %}">
                            <button>manage !</button>
                        </a>
                    </div>
                    <div class="card">
                        <i class="fas fa-palette"></i>
                        <h3>Add More Products</h3>
                        <p>add products to your inventory</p>
                        <a href="{% url 'regproduct'%}">
                            <button>add now!</button>
                        </a>
                    </div>
                    <div class="card">
                        <i class="fas fa-palette"></i>
                        <h3>Edit your profile</h3>
                        <p>edit your business information</p>
                        <a href="{% url 'edit_business'%}">
                            <button>edit now!</button>
                        </a>
                    </div>

                    <div class="card">
                        <i class="fab fa-app-store-ios"></i>
                        <h3>Log Out</h3>
                        
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="#">logout</button>
                            </form>
                        </li>
                    </div>
                </div>
                
                    
                </section>
            </section>      
        </div>
        <footer class="section-p1">
            <div class="col">
                <img class="logo"src="{% static 'images/logo.jpg' %}">
                <h4>Contact US</h4>
                <p><strong>address:</strong> P.O Box 28484 ,william street</p>
                <p><strong>phone:</strong> +256 456 938 456 ,+256 678 567 400</p>
                <div class="follow">
                    <h4>Follow us</h4>
                    <div class="icon">
                        <i class="fab fa-facebook-f">@eProx</i>
                        <i class="fab fa-twitter">@eProx</i>
                        <i class="fab fa-instagram">@eProx</i>
                        <i class="fab fa-pinterest-p">@eProx</i>
                        <i class="fab fa-youtube">@eProx</i>
                    </div>
                </div>
            </div>
            
            </div>
            <div class="col install">
                <p>Secured Payment Gateways</p>
                <img src="img/payment2.png">
            </div>
            <div class="copyright">
                <p> 2024 ,eprox -ecommerce copyright</p>
            </div>
        </footer>
        

    </body>
</html>

eProx/templates/eProx/business_products.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Other meta tags and links -->

    <!-- Add custom styles for Edit and Delete buttons -->
    <style>
        /* CSS for Edit and Delete buttons */
        .btn-edit,
        .btn-delete {
            display: inline-block;
            padding: 8px 16px;
            margin-right: 8px;
            font-size: 14px;
            font-weight: bold;
            text-decoration: none;
            color: #fff;
            background-color: #007bff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .btn-edit:hover,
        .btn-delete:hover {
            background-color: #0056b3;
        }

        /* Optional: Increase spacing between buttons */
        .actions-container {
            margin-top: 8px;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Boxicons -->
    <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static '/css/business_page.css' %}">

    <title>Inventory</title>
</head>
<body>

<!-- SIDEBAR -->
<section id="sidebar">
    <a href="{% url 'business1' %}" class="brand">
        <i class='bx bxs-smile'></i>
        <span class="text">eProx</span>
    </a>
    <ul class="side-menu top">
        <li>
            <a href="business_update_order.html">
                <i class='bx bx-list-ul' ></i>
                <span class="text">Recent orders</span>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'business_products' %}">
                <i class='bx bxs-shopping-bag-alt' ></i>
                <span class="text">My inventory</span>
            </a>
        </li>
        <li>
            <a href="{% url 'regproduct' %}">
                <i class='bx bxs-package' ></i>
                <span class="text">add products</span>
            </a>
        </li>
        
        <li>
            <a href="{% url 'profile_page' %}">
                <i class='bx bxs-group' ></i>
                <span class="text">Profile</span>
            </a>
        </li>
    </ul>
    <ul class="side-menu">
        <li>
            <a href="{% url 'logout' %}">
                <i class='bx bxs-log-out-circle' ></i>
                <span class="text">Logout</span>
            </a>
        </li>
    </ul>
</section>
<!-- SIDEBAR -->

<!-- CONTENT -->
<section id="content">
    <!-- NAVBAR -->
    <nav>
        <i class='bx bx-menu' ></i>
        <a href="#" class="nav-link">menu</a>
        <form action="#">
            <div class="form-input">
                <input type="search" placeholder="Search...">
                <button type="submit" class="search-btn"><i class='bx bx-search' ></i></button>
            </div>
        </form>
        <input type="checkbox" id="switch-mode" hidden>
        <label for="switch-mode" class="switch-mode"></label>
    </nav>
    <!-- NAVBAR -->

    <!-- MAIN -->
    <main>
        <div class="head-title">
            <div class="left">
                <h1>Inventory</h1>
                <ul class="breadcrumb">
                    <li>
                        <a href="{% url 'business1' %}">Home</a>
                    </li>
                    <li><i class='bx bx-chevron-right' ></i></li>
                    <li>
                        <a class="active" href="{% url 'business_products' %}">Inventory</a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="table-data">
            <div class="order">
                <div class="head">
                    <h3>My products</h3>
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Upload Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for product in products %}
                        <tr>
                            <td>
                                <div class="product-container">
                                    <img src="{{ product.picture.url }}" alt="{{ product.name }}">
                                    <h3>{{ product.name }}</h3>
                                    <!-- Add more product details as needed -->
                                </div>
                            </td>
                            <td>{{ product.upload_date|date:"F d, Y" }}</td>
                            <td>
                                <!-- Actions (edit/delete) buttons -->
                                <a href="{% url 'business_update_products' product.id %}" class="btn-edit">Edit</a>
                                <form action="{% url 'business_delete_product' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Delete" class="btn-delete">
                                </form>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="3">No products available.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </main>
    <!-- MAIN -->
</section>
<!-- CONTENT -->

<script src="{% static 'js/business_page.js' %}"></script>
</body>
</html>

eProx/templates/eProx/category.html
{% extends "eProx/navbar.html" %}
{% load static %}

{% block body%}
        <section id="hero">
            <h4>Eprox</h4>
            <h2>{{category}}</h2>
            
           
            <a href="#feature1"> <button>More info</button></a>

           

        </section>
     
        

        <section id="feature1" >
            <section id="product1" class="section-p1">
                <h2>Your {{category}} Products Here.....</h2>
                <p>new collection</p>
            
                <div class="pro-container">
                    {% for product in products %}
                    <div class="pro">
                        <img src="{{product.picture.url}}" alt="">
                        <div class="des">
                            <span>{{product.name}}</span>
                            <h5>{{product.description}}</h5>
                            
                            <h4>{{ product.price}}</h4>
                        </div>
                        <a href="{% url 'productcard' product.id %}"><button>VIEW PRODUCT</button></a>
                    </div>
                    {% endfor %}
                </div>
            </section>
            
        </section>
           
            

        
{% endblock body%}

eProx/templates/eProx/edit_business.html
{% load static%}




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Registration Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="{% static 'css/productreg.css' %}" rel="stylesheet" />

</head>
<body>
    <header>
        <h1>Edit Your Business Profile</h1>
    </header>

    <main>
        <form action=" " method='POST'  enctype="multipart/form-data">
            {% csrf_token %}
            <label for="productName">Business Name:</label>
            {{form.name}}

            <label for="productcategory">Business Email:</label>
            {{form.email}}

            <label for="productDescription">Business Description:</label>
            {{form.description}}

            <label for="productcategory">Business contacts:</label>
            {{form.contacts}}

            <label for="productPrice">Business location:</label>
            {{form.location}}

            

            <label for="productcategory">Business logo:</label>
            {{form.logo}}

            <button type="submit" >Save Changes</button>
            <button onclick= window.history.back()>CANCEL</button>
        </form>
    </main>

    <script>
        function registerProduct() {
            // You would typically use JavaScript to handle form submission and interact with the server.
            // In a real-world scenario, you would use AJAX or fetch to send data to the server.
            alert('Product registration functionality to be implemented.');
        }
    </script>
</body>
</html>

eProx/templates/eProx/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>eprox</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" >

        <link rel="stylesheet" href="{% static 'CSS/styles.css' %}">
    </head>
    <body>
        <section id="header">
            <a href="{%url 'home' %}"><img src="{% static 'images/logo.jpg' %}" class="logo" alt=""></a>
            <div>
                <ul id="navbar">
                   
                    <li><a  href="{%url 'home'%}">HOME</a></li>
                    <li><a class="#" href="{%url 'login'%}">Login</a></li>
                    <li><a class="active" href="#">Sign Up</a></li>
                    <!-- <li><a href="{%url 'logout'%}">logout</a></li>
                    <li><a href="{%url 'product'%}">Products</a></li>
                    <li><a href="profile.html">My profile</a></li>  -->
                    
                   
                    
                    
                    <!-- <li id="ig-cart"><a href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i></a></li> -->
                    <a href="#" id="close"><i class="fa fa-times"></i></a>
                </ul>
            </div>
            <div id="mobile">
                
                <a href="{%url 'cart:cart_detail' %}l"><i class="fa fa-shopping-cart"></i></a>
                <i id="bar" class="fas fa-outdent"></i>
            </div>
        </section>



    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'CSS/login.css' %}">
    
</head>
<body>
    <div class="container">
        <form action="." method="post">
        {% csrf_token %}
            <h2>Sign Up</h2>
            <div class="input-group">
                <label for="username">Username:</label>
                 {{form.username}}
            </div>
            <div class="input-group">
                <label for="password1">Password:</label>
                {{form.password1}}
            </div>
            <div class="input-group">
                <label for="password2">Confirm Password:</label>
                {{form.password2}}
            </div>
            <button type="submit">Sign Up</button>
        </form>
    </div>
</body>
</html>