G14_Suppliers/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('eProx.urls')),
    path('eProx/',include('django.contrib.auth.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls', namespace="order")),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create_order',views.create_order,name = 'create'),
    path('create/', views.order_create, name='order_create'),
    path('checkout/',views.checkoutDetails, name= 'checkout'),
    path('checkouted/', views.checkout_view,name='checkouted')
]

order/models.py
from django.db import models
from eProx.models import *

class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='checkouts')
    first_name = models.CharField(max_length=50, null= True)
    last_name = models.CharField(max_length=50, null= True)
    email = models.EmailField(null= True)
    address = models.CharField(max_length=250,null= True)
    created = models.DateTimeField(auto_now_add=True)
    product = models.ForeignKey(Product, null= True, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        total_cost = 0
        for item in self.items.all():
            total_cost += item.product.price * item.quantity
        return total_cost

class Order(models.Model):
    status_choices = [
        ('Pending', 'Pending'),
        ('Confirmed', 'Confirmed'),
        ('Delivered', 'Delivered'),
    ]
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    status = models.CharField(max_length=20, choices=status_choices, default='Pending')
    checkout = models.ForeignKey(Checkout, related_name='orders', on_delete=models.CASCADE)
    product = models.ManyToManyField(Product, through='OrderedProducts')

    class Meta:
        ordering = ['-date_ordered']
    # def __str__(self):
    #     return f"Order {self.id} by {self.customer}"
    def save(self, *args, **kwargs):
        if not self.checkout:
            self.checkout = Checkout.objects.create()
        super().save(*args, **kwargs)

    def get_ordered_products(self):
        return self.orderedproducts_set.all()

    def get_cart_items_count(self):
        return sum(item.quantity for item in self.get_ordered_products())

    def get_cart_total(self):
        return sum(item.get_total() for item in self.get_ordered_products())

    def __str__(self):
        return f'{self.customer.name} - Order No. {self.id}'

    @property
    def get_ordered_products(self):
        return self.checkout.items.all()

        
    @property
    def get_cart_total(self):
       orderitems = self.orderitem_set.all()
       total = sum([item.get_total for item in orderitems])
       return total

    @property
    def get_cart_items(self):
       orderitems = self.orderitem_set.all()
       total_items = sum(item.get_quantity for item in orderitems)
       return total_items

class OrderedProducts(models.Model):
    orders = models.ForeignKey(Order, on_delete=models.CASCADE, null = True)
    order = models.ForeignKey(Checkout, related_name='items', on_delete=models.CASCADE, null= True)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, null = True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        unique_together = (('order', 'product'),)

    def __str__(self):
        return  str(self.product) +  str(' order No. ')+ str(self.id) 
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    
    @property
    def get_quantity(self):
        total_quantity = self.quantity
        return total_quantity
    
    def get_cost(self):
        return self.price * self.quantity

order/forms.py
from django import forms
from .models import *


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = "__all__"


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Checkout
        fields = ('first_name','last_name','email','address')

order/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth import login as auth_login
from cart.cart import Cart
from .models import *
from .forms import *
from eProx.models import Business, Customer

def create_order(request):
    return render(request, 'order/create.html')
    

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():

            #creating a new user alongside the order
            user = User.objects.create_user(
                email = form.cleaned_data.get('email'),
                name = form.cleaned_data.get('first_name'),
                last_name = form.cleaned_data.get('last_name'),
                password = form.cleaned_data.get('password')
            )
            user.save()
            #update user fields to be used for the next order
            # user.address = form.cleaned_data.get('address')
            # user.postal_code = form.cleaned_data.get('postal_code')
            # user.city = form.cleaned_data.get('city')
            # auth_login(request, user)
            order = form.save()
            
            for item in cart:
                OrderedProducts.objects.create(order=order, product=item['product'],
                                         price=item['price'], quantity=item['quantity'])
            # clear the cart
            cart.clear()
            return render(request, 'order/created.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/create.html', {'cart': cart, 'form': form})

def make_order(request):
    #used to create orders for when a user is logged in
    form = CheckoutForm()
    cart = Cart(request)
    customer = request.user.customer
    
    owner = request.user
    checkout = Checkout.objects.create(
            user = owner,
            first_name = request.user.first_name,
            last_name = request.user.last_name,
            email = request.user.email,
            # postal_code = owner.postal_code,
            # city = owner.city
    )
    order = Order.objects.create(customer=customer, checkout=checkout)
    for item in cart:
        OrderedProducts.objects.create(order=order.checkout, product=item['product'],
                                    price=item['price'], quantity=item['quantity'])
    # clear the cart
    cart.clear()
    return render(request, 'order/created.html', {'order': order,'form':form,})

def checkoutDetails(request):
    user = request.user
    if request.method =="POST":
        form= CheckoutForm(request.POST,request.FILES)
        if form.is_valid(): #The business information must be valid for it to be saved in the database
            form.instance.user = user
            form.save()
            return redirect('home')
        else:
            return render(request,'eProx/homepage.html',{'form':form})
    else:           
        return render(request,'order/created.html',{'form':form}) 
    
def checkout_view(request):
    user = request.user
    business = Business.objects.get(user=user)
    orders_with_checkout = Order.objects.filter(checkout__business=business)

    return render(request, 'order/template', {
        'orders_with_checkout': orders_with_checkout,
    })

order/templates/order/create.html
{% load static %}
{% block title %}
Checkout
{% endblock %}
{%block content%}
<head>
  <link rel="stylesheet" href="{% static 'css/bootstrap4.css' %}">
</head>
<div class="container">
    <h1 class="text-center">Checkout</h1>
    <div class="order-info">
        <h3 class="text-center">Your order</h3>
        <ul style="display: inline;">
            {% for item in cart %}
            <li>
              <img src="{{ item.product.picture.url }}" alt="{{ item.product.name }}" style="max-width: 50px; max-height: 50px;">
                {{ item.quantity }}x {{ item.product.name }}
                <span>shs.{{ item.total_price }}</span>
            </li>
            {% endfor %}
        </ul>
        <h4>Total:shs.{{ cart.get_total_price }}</h4>
    </div>
    <section class="module">
      <div class="container">
        <div class="row">
          <div class="col-sm-5 col-sm-offset-1 mb-sm-40">
            <h4 class="font-alt">Login</h4>
            <hr class="divider-w mb-10">
            <form action="" class="form" method="POST">
              {% csrf_token %}
                  <div class="form-group">
                  <input class="form-control" id="email" type="text" name="email" placeholder="email"/>
                  </div>
                  <div class="form-group">
                  <input class="form-control" id="password" type="password" name="password" placeholder="Password"/>
                  </div>
                  <div class="form-group">
                  <button class="btn btn-round btn-b">Login</button>
                  </div>
            </form>
          </div>
          <div class="col-sm-5">
            <h4 class="font-alt">Register</h4>
            <hr class="divider-w mb-10">
              <form action="{% url 'order:order_create' %}" method="POST" class="order-form">
                  <br>
                  <p><input class="btn btn-primary btn-sm btn-block" type="submit" value="Place order"></p>
                  {% csrf_token %}
                      <div class="form-group">
                          <label for="username">Username:</label>
                          {{form.username}}
                      </div>
                      <div class="form-group">
                          <label for="password1">Password:</label>
                          {{form.password1}}
                      </div>
                      <div class="form-group">
                          <label for="password2">Confirm Password:</label>
                          {{form.password2}}
                      </div>
                      <button type="submit">Sign Up</button>
              </form>
          </div>
        </div>
      </div>
    </section>
    
</div>

<div>
    <label for="password">
        Confirm Password
    </label>
    <input type="password" name="password2" class="form-control">
</div>
{% endblock %}

order/templates/order/created.html
{% block content %}
<div class="container text-center mt-5 mb-5">
    <form action="{% url 'order:checkout' %}" method='POST'  enctype="multipart/form-data">
        {% csrf_token %}
        <label for="productcategory">First Name: </label>
        {{form.first_name}}

        <label for="productDescription">Last Name: </label>
        {{form.last_name}}

        <label for="productcategory">Email:</label>
        {{form.email}}

        <label for="productPrice">Business location:</label>
        {{form.address}}

        <button type="submit" >Submit</button>
    </form>
    <h1>Thank you</h1>
    <h3>Your order has been successfully completed. Your order number is
    <strong>{{ order.id }}</strong>.</h3>
</div>
{% endblock %}